name: Deploy React Vite App

on:
  push:
    branches:
      - main # 当你往 main 分支 push 代码时自动触发

# 赋予该工作流把打包产物写入 gh-pages 分支的绝对读写权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/workspace-node@v4 # 线上加载 Node 运行环境
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install # 使用 yarn 安装依赖

      - name: Build Project
        run: yarn build # 使用 yarn 进行本地无错打包
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 打包出来的文件夹叫 dist，将它推送到线上
          branch: gh-pages # 线上静态网站托管的分支
